### ISSUE TITLE
Tests started failing

### ISSUE THREAD

**Issue by gentlecat** [gentlecat/steam-locomotive#17]
Some of the tests started failing and need to be fixed. See https://travis-ci.org/gentlecat/steam-locomotive/jobs/350140725.

**Comment by bashilbers** [comment]
It looks like they don't allow CSV in the `appids` anymore. Can also be seen in this client: https://github.com/Autarc/steam-store/blob/c3d86a002c300333e2475dc6fed495da5221c577/lib/api/steam.js#L132

**Comment by bashilbers** [comment]
There is almost no documentation? Only a unofficial one..  🤔
